<?php

  function barbz_preprocess_page(&$variables) {
    $variables['site_name'] = \Drupal::config('system.site')->get('name');
    $variables['site_slogan'] = \Drupal::config('system.site')->get('slogan');
  }

  function barbz_preprocess_menu(&$variables) {
    $variables['site_name'] = \Drupal::config('system.site')->get('name');
    $variables['site_slogan'] = \Drupal::config('system.site')->get('slogan');
  }

  function barbz_preprocess_node(&$variables) {

  }

?>
